prjLookdayLogIn/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using prjLookdayLogIn.Models;
using prjLookdayLogIn.ViewModel;
using Register_and_login_test;
using System.Text;
using System.Text.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace prjLookdayLogIn.Controllers
{
    public class LogInController : Controller
    {
        private readonly lookdaysContext _context;
        public LogInController(lookdaysContext context)
        {
            _context = context;
        }
        public IActionResult userlogin()
        {
            return View();
        }

        public IActionResult pwdcheck(string email, string password)
        {
            //是 LINQ 中的一個方法，用於查詢序列中符合指定條件的唯一一個元素
            //如果沒有符合條件的使用者，則 users 變數將為 null
            var users = _context.Users.SingleOrDefault(x => x.Email == email);

            if (users != null)
            {
                //使用CCryptography.VerifyPassword方法驗證密碼
                bool isPasswordValid = CCryptography.VerifyPassword(password, users.Password, "gugubird");

                if (isPasswordValid) 
                {
                    return Json("True");
                }

                
            }
             
            return Json("False");

        }



        public IActionResult register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult register(User new_user)
        {
        
            if (string.IsNullOrEmpty(new_user.Username) || string.IsNullOrEmpty(new_user.Email) || string.IsNullOrEmpty(new_user.Password))
            {
                return BadRequest("姓名、電子信箱、密碼不能為空");
            }

            string hashedPassword = CCryptography.HashPasswordWithSalt(new_user.Password);
            new_user.Password = hashedPassword;

            if (new_user.RoleId == 0)
            {
                new_user.RoleId = 1;
            }

          // 新資料傳入資料庫中
                _context.Users.Add(new_user);
                _context.SaveChanges();
                return Ok("註冊成功");

        }


        public IActionResult checkaccount(string email)
        {

            // 檢查 _context.Members 中是否存在一個成員的名稱等於傳入的 name 參數。 如果存在，member 將被設置為 true，否則為 false。
            ////var users = _context.Users.Any(x => x.Email == email);

            ////return Content(users.ToString(), "text/plain", System.Text.Encoding.UTF8);

            // 检查数据库中是否存在具有特定邮箱的用户
            bool userExists = _context.Users.Any(x => x.Email == email);
            return Content(userExists.ToString(), "text/plain", System.Text.Encoding.UTF8);
        }

    }
}

prjLookdayLogIn/Views/LogIn/Index.cshtml
@model IEnumerable<prjLookdayLogIn.Models.Booking>

<h1>登入成功!!!!!</h1>

prjLookdayLogIn/Views/LogIn/register.cshtml
<div style="width:436px; max-height:619px;margin:auto; background-color: #FFAF60;border-radius: 20px 20px 20px 20px;">
    <div><img src="~/images/logofrmmain.png" style="width:180px; max-height:320px;" /></div>

    <div class="a1" style="max-height:525px;">
        @* 這表示表單數據將使用 HTTP POST 方法發送到指定的伺服器端點（在 action 屬性中指定） *@
        <form method="post" action="~/LogIn/register" id="form1" enctype="multipart/form-data">
            @*   <div>
            @* for 跟 id名稱要一樣 讓典籍標籤的時候聚焦到輸入框
            name屬性將再提交表單時將輸入的值作為名稱參數傳遞給伺服器 *@
            @*  <label for="txtName">請輸入姓名:</label>
            <br />
            <input type="text" id="txtName" name="name" />
            <div class="reminder"></div>
            </div> * *@
            <div style="text-align:center;">
                <h3>登入 / 註冊</h3>
                <span style="font-size:15px">註冊Lookday帳戶，享會員禮遇標籤商品專屬優惠價!</span>
            </div>
            <div>
                <label for="txtUsername" style="margin-left:128px; margin-left:80px;">請輸入用戶名稱:</label>
                <br />
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="text" id="txtUsername" name="username" style=" border-radius:10px 10px 10px 10px;width:280px; " required />
                </div>
                <div class="reminder" id="remindeusername" style="margin-left:80px;"></div>
            </div>
            <div>
                <label for="txtEmail" style="margin-left:80px;">請輸入電子郵件:</label>
                <br />
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="email" id="txtEmail" name="email" style="border-radius:10px 10px 10px 10px;width:280px; "required />
                </div>
                <div class="reminder" id="remindemail" style="margin-left:80px;"></div>
            </div>
            <div>
                <label for="txtPwd" style="margin-left:80px;">請輸入密碼</label>
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="password" id="txtPwd" name="password" style=" border-radius:10px 10px 10px 10px;width:280px;" required ;placeholder="長度至少八個字且須包含1個大小寫英文字母" />
                </div>
                <div class="reminder" id="remindpwd" style="margin-left:80px;">
                </div>
            </div>
            <div>
                <label for="checkPwd" style="margin-left:80px;">請再次確認密碼:</label>
                <br />
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="password" id="checkPwd" name="checkpassword" style=" border-radius:10px 10px 10px 10px;width:280px;" required />
                </div>


                <div style="border-color:darkgrey; text-align:center;">
                    <input type="hidden" id="roleID" value="1"/>
                </div>



                <div class="reminder" id="remindcheckpwd" style="margin-left:80px;"></div>
            </div>
            <div>
                <input type="hidden" id="roleID" />
            </div>
            <br />
            <button type="submit" id="btnsubmit" style="margin-left:80px;;border-radius:10px 10px 10px 10px;width:280px;" required>送出</button>
            <div class="reminder" id="remindsubmit" style="margin-left:128px;"></div>
        </form>
    </div>



</div>

@section Styles {
    <style>
        .reminder {
            color: red;
        }

    </style>
}


@section Scripts {
    <script>
        let txtusername = document.getElementById('txtUsername');
        let useremail = document.getElementById('txtEmail');
        let userpwd = document.getElementById('txtPwd');
        let usercheckpwd = document.getElementById('checkPwd');
        let remindeusername = document.getElementById('remindeusername');
        let remindemail = document.getElementById('remindemail');
        let remindpwd = document.getElementById('remindpwd');
        let remindcheckpwd = document.getElementById('remindcheckpwd');

        let btnsubmit = document.getElementById('btnsubmit');
        let remindsubmit = document.getElementById('remindsubmit');

        // console.log(userbirthday);

        // txtusername.addEventListener('blur', () => {

        //     if (txtusername.value == "") {
        //         remindeusername.textContent = "*請輸入使用者名稱"
        //     }
        //     else {
        //         remindeusername.textContent = "";
        //     }

        // });

        useremail.addEventListener('blur', async () => {

            // if (useremail.value == "") {
            //     remindemail.textContent = "*請輸入電子信箱";
            // }
            // else {
                let url = "@Url.Content("~/LogIn/checkaccount/")?email" + useremail.value;

                let response = await fetch(url);
                let data = await response.text();

                if (data == "True") {
                    remindemail.textContent = "*電子郵件已註冊，請重新輸入";
                }
                else {
                    remindemail.textContent = "";
                    return;
                }
            // }

            
        })

        userpwd.addEventListener('blur', () => {

            let pwd = userpwd.value;
            // 檢查密碼是否長度大於等於8
            let lengthcheck = pwd.length >= 8;
            // 檢查密碼是否包含至少一個大寫字母
            let uppercasecheck = /[A-Z]/.test(pwd);
            // 檢查密碼是否包含至少一個小寫字母
            let lowercasecheck = /[a-z]/.test(pwd);

            if (lengthcheck && uppercasecheck && lowercasecheck) {
                remindpwd.textContent = '';
            } else {
                // 如果長度檢查不通過，設置相應的錯誤信息
                if (!lengthcheck) {
                    remindpwd.textContent = '*請輸入長度大於8的密碼';
                }
                // 如果大寫字母檢查不通過，設置相應的錯誤信息
                else if (!uppercasecheck) {
                    remindpwd.textContent = '*密碼中必須包含至少一個大寫字母';
                }
                // 如果小寫字母檢查不通過，設置相應的錯誤信息
                else if (!lowercasecheck) {
                    remindpwd.textContent = '*密碼中必須包含至少一個小寫字母';
                }
                event.preventDefault(); // 阻止表單的提交
            }
        });


        usercheckpwd.addEventListener('blur', () => {
            if (usercheckpwd.value !== userpwd.value) {
                remindcheckpwd.textContent = '*密碼輸入錯誤，請重新輸入';
            } else {
                remindcheckpwd.textContent = '';
            }
        });


        // btnsubmit.addEventListener('click', async (event) => {
        //     event.preventDefault(); // 阻止表單的提交

        //     let form1 = document.getElementById('form1');
        //     let formdata = new FormData(form1);

        //     //let url = `@Url.Content("~/LogIn/register/")`;
        //     let url = `@Url.Action("register", "LogIn")`;

           
        //         let response = await fetch(url, {
        //             method: 'POST',
        //             body: formdata
        //         });

        //         if (!response.ok) {
        //             let errorMessage = `HTTP 錯誤! 狀態: ${response.status}`;
        //             console.error(errorMessage);
        //             console.error(await response.text()); // 打印响应内容以获取更多调试信息
        //             throw new Error(errorMessage);
        //         }

        //         let data = await response.json();
        //         if (data.success) {
        //             remindsubmit.textContent = "註冊成功";
        //         }
        //         else {
        //             remindsubmit.textContent = "錯誤:${data.message }";
        //         }
           
        // })

    </script>
}

prjLookdayLogIn/Views/LogIn/userlogin.cshtml
<div class="main-container" style="width:436px; max-height:619px;margin:auto;">
    <div><img src="~/images/logofrmmain.png" style="width:180px; max-height:320px;" /></div>
   

    <div class="a1" style="max-height:525px;">
        <div>
            <div>
                <div style="text-align:center;">
                    <h3>登入 / 註冊</h3>
                    <span style="font-size:15px">註冊Lookday帳戶，享會員禮遇標籤商品專屬優惠價!</span>
                </div>
               @*  <label class="label" for="email" >請輸入帳號</label> *@
                <br />
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="email" id="email" placeholder="請輸入電子信箱" style="border-radius:10px 10px 10px 10px;width:280px; border-color:white; " required="required" ; />
                </div>
                <div class="reminder" id="reminder" style="margin-left:80px;"></div>


            @*     <label class="label" for="pwd">請輸入密碼</label> *@
                <br />
                <div style="border-color:darkgrey; text-align:center;">
                    <input type="password" id="pwd" placeholder="請輸入密碼" style="border-radius:10px 10px 10px 10px;width:280px; border-color:white;" required="required" ; />
                    <br />
                </div>
                <div class ="reminder" id="pwdreminder" ></div>
                <div style="text-align:center">
             
                <label class="noaccount">還沒有帳號嗎? </label>
                <a class="noaccount" href="https://localhost:7095/LogIn/register">點我註冊</a>
                    <br /> <br />
                </div>
                <div>
                    <button id="loginbtn" style="margin-left:310px; border-radius:5px 5px 5px 5px">登入</button>
                <br />
                </div>
                <div style="text-align:center">
                    <span style="font-size:15px ; color:gainsboro;">———————————或快速登入———————————</span>
                    <br /> <br />
                </div>
                <div style="display:flex; justify-content:center;">
                    <div style="margin-right:20px;"><img src="~/images/googlelogo.svg" id="google-login-button" /></div>
                    <div style="margin-right:20px;"><img src="~/images/fblogo.svg" />
                </div>
                    <div><img src="~/images/applelogo.svg" /></div>
                </div>
                <div id="btn-container">
                    <button id="customerbtn" style="margin-right:300px; border-color:transparent; background-color:transparent;text-decoration:underline;">顧客</button>
                    <button id="empbtn" style="border-color:transparent; background-color:transparent;text-decoration:underline;">員工</button>
                </div>
                <div>
                    <p style="font-size:13px; margin-left:30px;">
                        註冊或登入即表示你了解並同意Lookday
                        <a href="https://www.klook.com/zh-TW/conditions/" target="_blank">服務條款</a>
                        與
                        <a href="https://www.klook.com/zh-TW/policy/" target="_blank">隱私權條款</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <style>
        .main-container {
            width: 50% ;
            height:80%;
            /*  line-height:50px;
                                   padding:10px; */
            background-color: #FFAF60;
            /*            color:red; */
            border-radius: 15px 15px 15px 15px;
        }

        .noaccount {
            font-size: 12px;
        }

        .reminder {
            color: red;
        }

        #loginbtn {
            display: flex;
            align-content: center;
        }

        #btn-container {
            display: flex;
            justify-content: space-evenly;
            margin-top: 20px;
        }

    </style>
}


@section Scripts {
    <script>
        let loginaccount = document.getElementById('email');
        let pwd = document.getElementById('pwd');

        let remind = document.getElementById('reminder');
        let pwdreminder = document.getElementById('pwdreminder');

        let loginbtn = document.getElementById('loginbtn');
        let customerbtn = document.getElementById('customerbtn');
        let empbtn = document.getElementById('empbtn');

        loginbtn.addEventListener('click', async (event) => {
            event.preventDefault();

            let url = `@Url.Content("~/LogIn/pwdcheck/")?email=${loginaccount.value}&password=${pwd.value}`;
            let response = await fetch(url);

            //json()
            let data = await response.json();

            console.log(data);


            // 確保兼容字串 "True" 和布林值 true
            if (data === "True" || data === true) {
                remind.textContent = "";
                alert("登入成功");
                //return Ok("登入成功");
                // return RedirectToAction("Home");
                window.location.href = '@Url.Action("Index", "Home")';
            }
            else {
                remind.textContent = "*帳號/密碼輸入錯誤";
            }

        });

        customerbtn.addEventListener('click', () => {
            loginaccount.value = '789@gmail.com';
            pwd.value = 'Aa111111';
        });

        empbtn.addEventListener('click', () => {
            loginaccount.value = 'shaw@gmail.com';
            pwd.value = 'Aa111111';
        })

    </script>
}